# Generated by Django 5.2.10 on 2026-01-07 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('couleur', models.CharField(help_text='Code hexadécimal de la couleur', max_length=7)),
                ('couleur_fond', models.CharField(help_text='Code hexadécimal de la couleur de fond', max_length=7)),
            ],
            options={
                'verbose_name': "État d'affaire",
                'verbose_name_plural': "États d'affaires",
            },
        ),
        migrations.CreateModel(
            name='MarcheGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('nombre_projet', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Marché global',
                'verbose_name_plural': 'Marchés globaux',
            },
        ),
        migrations.CreateModel(
            name='MarcheDetaille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=50)),
                ('nom_marche', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('objet', models.CharField(max_length=200)),
                ('nom_client', models.CharField(max_length=100)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('etat_affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marches.etataffaire')),
                ('resp_marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.profile')),
                ('marche_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marches_detailles', to='marches.marcheglobal')),
            ],
            options={
                'verbose_name': 'Marché détaillé',
                'verbose_name_plural': 'Marchés détaillés',
                'ordering': ['-date_maj'],
            },
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('objet', models.CharField(blank=True, max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cartes_images/')),
                ('nom_client', models.CharField(blank=True, max_length=100)),
                ('date_retour', models.DateField()),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('marche_detaille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes', to='marches.marchedetaille')),
            ],
            options={
                'verbose_name': 'Carte',
                'verbose_name_plural': 'Cartes',
            },
        ),
    ]
