# Generated by Django 5.2.10 on 2026-01-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NomMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('demande_demarche', models.BooleanField(default=False, help_text='Cocher si une démarche doit être saisie')),
            ],
        ),
        migrations.AddField(
            model_name='carte',
            name='demarche_solution',
            field=models.TextField(blank=True, help_text='À remplir uniquement si la solution choisie l’exige'),
        ),
        migrations.AddField(
            model_name='carte',
            name='nom_dossier',
            field=models.CharField(blank=True, help_text='Nom du dossier associé', max_length=200),
        ),
        migrations.AlterField(
            model_name='etataffaire',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='marchedetaille',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='marcheglobal',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='nom_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marches.nomclient'),
        ),
        migrations.AlterField(
            model_name='marchedetaille',
            name='nom_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marches.nomclient'),
        ),
        migrations.AlterField(
            model_name='marchedetaille',
            name='nom_marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marches.nommarche'),
        ),
        migrations.AddField(
            model_name='marchedetaille',
            name='prestation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='marches.prestation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carte',
            name='solution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='marches.solution'),
            preserve_default=False,
        ),
    ]
