# Generated by Django 5.2.10 on 2026-01-09 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        ('marches', '0002_nomclient_nommarche_prestation_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchedetaille',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marches.solution'),
        ),
        migrations.RemoveField(
            model_name='marchedetaille',
            name='nom_client',
        ),
        migrations.RemoveField(
            model_name='marchedetaille',
            name='resp_marche',
        ),
        migrations.AddField(
            model_name='marchedetaille',
            name='nom_client',
            field=models.ManyToManyField(related_name='marches_client', to='marches.nomclient'),
        ),
        migrations.AddField(
            model_name='marchedetaille',
            name='resp_marche',
            field=models.ManyToManyField(related_name='marches_resp', to='authentification.profile'),
        ),
    ]
