# Generated by Django 5.2.10 on 2026-01-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0003_marchedetaille_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchedetaille',
            name='prestation',
        ),
        migrations.AddField(
            model_name='marchedetaille',
            name='prestation',
            field=models.ManyToManyField(related_name='marches_prestation', to='marches.prestation'),
        ),
    ]
