# Generated by Django 5.2.10 on 2026-01-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0004_remove_marchedetaille_prestation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchedetaille',
            name='solution',
        ),
        migrations.AddField(
            model_name='carte',
            name='date_livraison',
            field=models.DateField(blank=True, help_text='À remplir uniquement si la solution choisie l’exige', null=True),
        ),
    ]
