# Generated by Django 5.2.10 on 2026-01-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0005_remove_marchedetaille_solution_carte_date_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchedetaille',
            name='nom_client',
            field=models.ManyToManyField(blank=True, related_name='marches_client', to='marches.nomclient'),
        ),
    ]
