# Generated by Django 5.2.10 on 2026-01-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        ('marches', '0006_alter_marchedetaille_nom_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchedetaille',
            name='resp_marche',
            field=models.ManyToManyField(blank=True, related_name='marches_resp', to='authentification.profile'),
        ),
    ]
