# Generated by Django 5.2.10 on 2026-01-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0007_alter_marchedetaille_resp_marche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchedetaille',
            name='prestation',
            field=models.ManyToManyField(blank=True, related_name='marches_prestation', to='marches.prestation'),
        ),
    ]
