# Generated by Django 5.2.10 on 2026-01-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0008_alter_marchedetaille_prestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchedetaille',
            name='objet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='marchedetaille',
            name='titre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
