# Generated by Django 5.2.10 on 2026-01-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0009_alter_marchedetaille_objet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchedetaille',
            name='objet',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='marchedetaille',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
