# Generated by Django 5.2.10 on 2026-01-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches', '0010_alter_marchedetaille_objet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='nom_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marches.nomclient'),
        ),
    ]
